spring:
  profiles: 
    active:
      - dev
  application:
    name: backing-service
  zipkin:
    base-url: ${ZIPKIN_HOST:http://localhost:9411}
eureka:
  client:
    service-url:
      defaultZone: ${REGISTER_CENTER:http://localhost:12331/eureka/}  
logging:
  config: ./config/log4j2.xml
---
spring:
  profiles: dev   
server:
  port: 8083
---
spring:
  profiles: prod
server:
  port: 80
eureka:
  instance:
    prefer-ip-address: true

